### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by saurabh-mk** [pbastide/PhylogeneticEM#16]
Hello,
This sounds like a method that I would like to use to detect shifts in some traits of interest. However, I was having trouble installing the package from downloaded zip files for all three branches.

Here's the error-

Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0\016O|I\0\0\0\0\0\0\0\0\0\0\0\0\027\0\t\0PhylogeneticEM-develop/UT\005\0\001\xcco<XPK\003\004\n\0\0\0\b\0\016O|I\xbb@\x84#\x96\0\0\0\xe9\0\0\0$\0\t\0Phylogen'
Warning in install.packages :
installation of package had non-zero exit status

Many thanks for the method,
Saurabh

**Comment by pbastide** [comment]
Hi Saurabh,

Thank you for your interest in the PhylogeneticEM method !

How exactly did you try to install the package ? On my end, I can install the package using `devtools`:
```R
install.packages("devtools")
devtools::install_github(repo = "pbastide/PhylogeneticEM", ref = "develop")
```
Could you try this on on your machine, and tell me how it went ?

Also, the package is almost ready, but still needs some polishing. I'm working on it, and should release a first official CRAN stable version soon. This means that some of the functions might evolve a little bit during the next month or so, and that some bugs might still show up. Please just remember to check for the updates. I'll make an announcement when the first version will be on the CRAN.

If you try it on, please let me know how it goes, any feedback is welcome !

Thank you,
Paul

**Comment by saurabh-mk** [comment]
Hello,

Earlier I had some issue with install_github() due to problems in SSL CA certificates at my end. Now I have fixed those issues, and it installs correctly.

However, in case it is relevant- the previously reported error still comes up if I download zip files and install using those.

Thanks for your help!
Saurabh

**Comment by pbastide** [comment]
Hi Saurabh,

Thank you for your feedback !
Also, I wanted to let you know that the first version (1.0.0) is now on CRAN: https://cran.rstudio.com/web/packages/PhylogeneticEM/

Regards,
Paul
