### ISSUE TITLE
Problem with plot function when working on univariate traits

### ISSUE THREAD

**Issue by mahendra-mariadassou** [pbastide/PhylogeneticEM#17]
MWE:
```
library(PhylogeneticEM)
## anolis data available in attached zip file
tree <- read.tree("anolis.phy")
traits <- read.csv("anolisDataAppended.csv", row.names = 1)
traits <- t(data.matrix(traits[ , "SVL", drop = FALSE])) ## unvariate trait
## Inference
res <- PhyloEM(phylo = tree,
               Y_data = traits,
               process = "OU",                     ## OU model
               random.root = TRUE,                 ## Root is stationary (true model)
               stationary.root = TRUE, 
               K_max = 10,                         ## Maximal number of shifts
               parallel_alpha = TRUE,              ## This can be set to TRUE for
               Ncores = 4)                         ## parallel computations
## Failing command
plot(res)
```

Results in the following error:
```
compute_ancestral_traits(x, params, method.selection, what, ...) でエラー: 
  The user specified parameters must be of class 'params_process'.
```

The problems seems to arise from https://github.com/pbastide/PhylogeneticEM/blob/5fd06963e45168c73f5807ff76570b137797a0b4/R/plot_functions.R#L324-L325 as 
`params[[traits]]]` returns a list instead of an object of class `params_process`

[anolis.zip](https://github.com/pbastide/PhylogeneticEM/files/3106616/anolis.zip)

**Comment by pbastide** [comment]
Thank you for reporting this issue ! I had several problems with the plotting function for univariate traits, and I tried to fix some of them in the `develop` branch.

When I run your MWE from this `develop` branch, I do not get the error you describe on my machine. Could you try again on your end, first installing the lastest version (with`devtools::install_github(repo = "pbastide/PhylogeneticEM", ref = "develop")`) ?

Let me know if it works !

**Comment by mahendra-mariadassou** [comment]
Works much better, thank you.
