### ISSUE TITLE
limiting shift locations

### ISSUE THREAD

**Issue by ptitle** [pbastide/PhylogeneticEM#22]
Is it possible to limit the locations of shifts to a set of specific nodes?

**Comment by pbastide** [comment]
Hi,

Thank you for your question, and sorry for my very late answer.

It is not possible in the current interface to limit the location of shifts to a set of specific nodes.

PhyloEM shift detection algorithms and model selection procedure assume that shifts can happen anywhere on the tree, and tries to find the best possible configuration. If shifts are limited to a set of nodes, that might change the dimension of the collection of models, and possibly impacts the model selection.

I don't know what is the biological question, but, just in case, if you are interested in comparing a limited set of hypothesis for shift locations, then other tools (such as mvMORPH) could be appropriate.

Thanks !

**Comment by ptitle** [comment]
Understood, thank you!

**Comment by jakeberv** [comment]
Hey Pascal -- thought you might find this relevant. https://github.com/pbastide/PhylogeneticEM/issues/23

I also came up with a work-around way to do this (and assess the resulting false positive rate) using l1ou if interested here: https://www.biorxiv.org/content/10.1101/2022.10.21.513146v1
